### ISSUE TITLE
Dependency mismatch

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/code_transformers#26]
Recently (2552119581f) code transformers changed its dependency to:
```
  analyzer: '>=0.15.6 <0.27.0'
```

This broke reflectable. In reflectable we had a dependency:
```
  analyzer: '^0.25.0'
```

We got a failure with the stack-trace:
```
ERROR: Check transforms
  Test failed: Caught AnalysisException: <rethrow>
  Caused by The null object does not have a getter 'importsAndExports'.
  
  NoSuchMethodError: method not found: 'importsAndExports'
  Receiver: null
  Arguments: []
  #0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6510:7)
  #1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6479:7)
  #2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2908:12)
  #3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3517:17)
  #4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3546:14)
  #5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1719:7)
  #6      ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:157:25)
  #7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
  #8      ListIterable.toList (dart:_internal/iterable.dart:219)
  #9      ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:158:10)
  #10     _rootRunUnary (dart:async/zone.dart:911)
  #11     _CustomZone.runUnary (dart:async/zone.dart:811)
  #12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
  #13     _Future._propagateToListeners (dart:async/future_impl.dart:577)
  #14     _Future._completeWithValue (dart:async/future_impl.dart:368)
  #15     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
  #16     _rootRun (dart:async/zone.dart:904)
  #17     _CustomZone.run (dart:async/zone.dart:803)
  #18     _CustomZone.runGuarded (dart:async/zone.dart:709)
  #19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
  #20     _microtaskLoop (dart:async/schedule_microtask.dart:43)
  #21     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
  #22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
  #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```
I haven't investigated this error, but updating to analyzer 0.26 seemed to mitigate the problem.

So it seems the newest code-transformers is incompatible with analyzer 0.25. We fixed it in reflectable, but it might be worth making a stricter dependency for code-transformers, or make it be really compatible with older versions.

**Comment by jakemac53** [comment]
Ah yep  you are right, I can work on resolving this.

**Comment by jakemac53** [comment]
I have published a new version with the new lower bound of 0.26, but unfortunately other users will still run into this if they have a constraint on analyzer <0.26 (because they will get the broken version of code_transformers).
